import { useRef, type CSSProperties, type MouseEventHandler } from "react";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";

interface ArrowProps {
    /** Size/position it from the outside, e.g. <Arrow style={{ width: 240 }} /> */
    className?: string;
    style?: CSSProperties;
    /** notified when the artwork is clicked */
    onClick?: MouseEventHandler<SVGSVGElement>;
}

/**
 * Bananatrees - generated by Stew Factory.
 * Trigger: load · loops
 * Deps:  npm i gsap @gsap/react
 *
 * Sizing: the SVG fills its container by default - wrap it in a sized element,
 * or pass className / style (e.g. style={{ width: 240, height: 240 }}).
 * overflow:visible lets motion extend past the frame (matches the editor).
 */
export default function Arrow({ className, style, onClick }: ArrowProps = {}) {
    const root = useRef<SVGSVGElement>(null);

    useGSAP(() => {
        const tl = gsap.timeline({ repeat: -1 });

        // path-7j5r-ce200a7f · rotate
        gsap.set("#path-7j5r-ce200a7f-a", { rotation: 0, transformOrigin: "50.000025236192904% 50.000011955837245%" });
        tl.to("#path-7j5r-ce200a7f-a", { rotation: 368.89, duration: 0.689, ease: "power1.inOut" }, 0);
        tl.to("#path-7j5r-ce200a7f-a", { rotation: 464.11, duration: 0.663, ease: "power1.inOut" }, 0.689);
        tl.to("#path-7j5r-ce200a7f-a", { rotation: 464.11, duration: 1.114, ease: "power1.inOut" }, 1.352);
        tl.to("#path-7j5r-ce200a7f-a", { rotation: 279.06, duration: 0.741, ease: "power1.inOut" }, 2.466);
        tl.to("#path-7j5r-ce200a7f-a", { rotation: 279.06, duration: 0.559, ease: "power1.inOut" }, 3.207);
        tl.to("#path-7j5r-ce200a7f-a", { rotation: 464.96, duration: 0.577, ease: "power1.inOut" }, 3.766);
        tl.to("#path-7j5r-ce200a7f-a", { rotation: 464.96, duration: 0.426, ease: "power1.inOut" }, 4.343);
        tl.to("#path-7j5r-ce200a7f-a", { rotation: 739.62, duration: 1.032, ease: "power1.inOut" }, 4.768);

        // path-7j5r-ce200a7f · x
        gsap.set("#path-7j5r-ce200a7f-a", { x: 0, transformOrigin: "50.000025236192904% 50.000011955837245%" });
        tl.to("#path-7j5r-ce200a7f-a", { x: 7.48, duration: 1.114, ease: "power1.inOut" }, 1.352);
        tl.to("#path-7j5r-ce200a7f-a", { x: 7.48, duration: 0.741, ease: "power1.inOut" }, 2.466);
        tl.to("#path-7j5r-ce200a7f-a", { x: -1.66, duration: 0.559, ease: "power1.inOut" }, 3.207);
        tl.to("#path-7j5r-ce200a7f-a", { x: -1.66, duration: 0.577, ease: "power1.inOut" }, 3.766);
        tl.to("#path-7j5r-ce200a7f-a", { x: 0, duration: 0.426, ease: "power1.inOut" }, 4.343);

        // path-7j5r-ce200a7f · y
        gsap.set("#path-7j5r-ce200a7f-a", { y: 0, transformOrigin: "50.000025236192904% 50.000011955837245%" });
        tl.to("#path-7j5r-ce200a7f-a", { y: 47.38, duration: 1.114, ease: "power1.inOut" }, 1.352);
        tl.to("#path-7j5r-ce200a7f-a", { y: 47.38, duration: 0.741, ease: "power1.inOut" }, 2.466);
        tl.to("#path-7j5r-ce200a7f-a", { y: -68.16, duration: 0.559, ease: "power1.inOut" }, 3.207);
        tl.to("#path-7j5r-ce200a7f-a", { y: -68.16, duration: 0.577, ease: "power1.inOut" }, 3.766);
        tl.to("#path-7j5r-ce200a7f-a", { y: 0, duration: 0.426, ease: "power1.inOut" }, 4.343);

        // path-7j5r-ce200a7f · scaleX
        gsap.set("#path-7j5r-ce200a7f-a", { scaleX: 1, transformOrigin: "50.000025236192904% 50.000011955837245%" });
        tl.to("#path-7j5r-ce200a7f-a", { scaleX: 1.002, duration: 1.751, ease: "power1.inOut" }, 0);

        // path-7j5r-ce200a7f · scaleY
        gsap.set("#path-7j5r-ce200a7f-a", { scaleY: 1, transformOrigin: "50.000025236192904% 50.000011955837245%" });
        tl.to("#path-7j5r-ce200a7f-a", { scaleY: 0.979, duration: 0.89, ease: "power1.inOut" }, 0);
        const cleanups: (() => void)[] = [];

        // path-7j5p-ab35d4c7 · dashflow
        {
            const __el = root.current?.querySelector("#path-7j5p-ab35d4c7") as SVGGraphicsElement | null;
            const __cycle = (__el?.getAttribute("stroke-dasharray") ?? "").split(/[\s,]+/).map(Number).filter(n => n > 0).reduce((a, b) => a + b, 0);
            if (__el && __cycle) gsap.to(__el, { attr: { "stroke-dashoffset": -__cycle }, duration: 1, ease: "none", repeat: -1 });
        }
        return () => cleanups.forEach((fn) => fn());
    }, { scope: root });

    return (
        <svg ref={root} id="svg-2" xmlns="http://www.w3.org/2000/svg" viewBox="-164.52 125.3 674.73 438.64" fill="#D9D9D9" fillOpacity="1" stroke="none" strokeWidth="0" strokeOpacity="1" strokeLinecap="butt" strokeLinejoin="miter" strokeDasharray="" onClick={onClick} className={className} style={{ overflow: "visible", ...style }}>
            <g id="path-7j5p-ab35d4c7-a">
                <path id="path-7j5p-ab35d4c7" d="M -128.37 432.14 C -52.33 396.78 142.91 289.21 228.26 285.17 C 291.43 285.17 335.86 295.89 366.41 343.8 C 415.71 415.31 346.97 527.79 198.39 527.79 C 115.07 492.38 90.28 389.92 131.01 317.37 C 170.32 247.36 330.14 195.77 403.45 189.69" fill="none" stroke="#000000" strokeWidth="9.3" strokeOpacity="1" strokeLinecap="round" strokeLinejoin="miter" strokeDasharray="28 28" fillOpacity="1" />
            </g>
            <g id="path-7j5r-ce200a7f-a">
                <g transform="matrix(1,0,0,1,0.83,6.87)">
                    <path id="path-7j5r-ce200a7f" d="M 416.84 169.45 L 424.73 173.9 C 427.87 175.67 429.44 179.32 428.56 182.82 L 425.66 194.39 C 424.25 199.99 430.78 204.15 435.26 200.52 L 465.21 176.21 C 471.06 171.46 467.7 162 460.17 162 L 418.79 162 C 414.7 162 413.27 167.44 416.84 169.45 Z" fill="#000000" stroke="none" strokeLinecap="round" strokeLinejoin="round" fillOpacity="1" strokeWidth="0" strokeDasharray="" />
                </g>
            </g>
        </svg>
    );
}
