import { useRef, type CSSProperties, type MouseEventHandler } from "react";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";

/** the "rect-2qkm33a" image - the image prop replaces it. The export baked the
 *  PNG in as base64 (185KB of JS); it lives in public/logos as a small webp. */
const DEFAULT_IMAGE = "/logos/jetix.webp";

interface JetixLogoProps {
  /** Size/position it from the outside, e.g. <JetixLogo style={{ width: 240 }} /> */
  className?: string;
  style?: CSSProperties;
  /** notified when the artwork is clicked */
  onClick?: MouseEventHandler<SVGSVGElement>;
  /** image href of the "rect-2qkm33a" element (default: the baked-in artwork) */
  image?: string;
}

/**
 * JetixLogo - generated by Stew Factory.
 * Trigger: load · loops
 * Image props: image
 * Deps:  npm i gsap @gsap/react
 *
 * Sizing: the SVG fills its container by default - wrap it in a sized element,
 * or pass className / style (e.g. style={{ width: 240, height: 240 }}).
 * overflow:hidden clips the artwork to the scene frame.
 */
export default function JetixLogo({ className, style, onClick, image = DEFAULT_IMAGE }: JetixLogoProps = {}) {
  const root = useRef<SVGSVGElement>(null);

  useGSAP(() => {
    const tl = gsap.timeline({ repeat: -1 });
    tl.to({}, { duration: 3 }, 0); // hold to the full length
    
    // rect-2qkm33a · pivot - stepped transform-origin (smoothOrigin keeps the tumble continuous)
    gsap.set("#rect-2qkm33a-a", { transformOrigin: "49.15138824727186% 99.11146013932661%", smoothOrigin: true });
    tl.set("#rect-2qkm33a-a", { transformOrigin: "49.15138824727186% 99.11146013932661%", smoothOrigin: true }, 0);
    
    // rect-2qkm33a · scaleX
    gsap.set("#rect-2qkm33a-a", { scaleX: 1 });
    tl.to("#rect-2qkm33a-a", { scaleX: 0.996, duration: 0.33, ease: "power1.inOut" }, 0);
    tl.to("#rect-2qkm33a-a", { scaleX: 0.934, duration: 0.229, ease: "power1.inOut" }, 0.33);
    tl.to("#rect-2qkm33a-a", { scaleX: 1, duration: 0.172, ease: "power1.inOut" }, 0.56);
    
    // rect-2qkm33a · scaleY
    gsap.set("#rect-2qkm33a-a", { scaleY: 1 });
    tl.to("#rect-2qkm33a-a", { scaleY: 0.698, duration: 0.33, ease: "power1.inOut" }, 0);
    tl.to("#rect-2qkm33a-a", { scaleY: 1.139, duration: 0.229, ease: "power1.inOut" }, 0.33);
    tl.to("#rect-2qkm33a-a", { scaleY: 1, duration: 0.106, ease: "power1.inOut" }, 0.56);
    tl.to("#rect-2qkm33a-a", { scaleY: 0.698, duration: 0.125, ease: "power1.inOut" }, 0.666);
    tl.to("#rect-2qkm33a-a", { scaleY: 1, duration: 0.088, ease: "power1.inOut" }, 0.791);
    
    // rect-2qkm33a · x
    gsap.set("#rect-2qkm33a-a", { x: 0 });
    tl.to("#rect-2qkm33a-a", { x: -1.6, duration: 0.56, ease: "power1.inOut" }, 0);
    tl.to("#rect-2qkm33a-a", { x: 0, duration: 0.172, ease: "power1.inOut" }, 0.56);
    
    // rect-2qkm33a · y
    gsap.set("#rect-2qkm33a-a", { y: 0 });
    tl.to("#rect-2qkm33a-a", { y: -123.59, duration: 0.229, ease: "power1.inOut" }, 0.33);
    tl.to("#rect-2qkm33a-a", { y: 0, duration: 0.172, ease: "power1.inOut" }, 0.56);
  }, { scope: root });

  return (
    <svg ref={root} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" onClick={onClick} className={className} style={{ overflow: "hidden", ...style }}>
      <defs>
        <clipPath id="JetixLogo-frame-clip"><rect x="0" y="0" width="512" height="512" /></clipPath>
      </defs>
      <g clipPath="url(#JetixLogo-frame-clip)">
      <defs>
        <pattern id="stew-rect-2qkm33a-img" patternUnits="userSpaceOnUse" x="66" y="149.16" width="378.27" height="241.84">
          <image x="0" y="18.02" width="378.27" height="205.8" preserveAspectRatio="none" href={image} />
        </pattern>
      </defs>
      <rect x="0" y="0" width="512" height="512" fill="#4c4c4c" />
      <g id="rect-2qkm33a-a">
        <g transform="matrix(1,0,0,1,-20,-20.5)">
          <rect id="rect-2qkm33a" x="66" y="149.16" width="378.27" height="241.84" fill="url(#stew-rect-2qkm33a-img)" />
        </g>
      </g>
      </g>
    </svg>
  );
}
