import { useRef, type CSSProperties, type MouseEventHandler } from "react";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";

interface NadirProps {
  /** Size/position it from the outside, e.g. <Nadir style={{ width: 240 }} /> */
  className?: string;
  style?: CSSProperties;
  /** notified when the artwork is clicked */
  onClick?: MouseEventHandler<SVGSVGElement>;
}

/**
 * Nadir - generated by Stew Factory.
 * Trigger: load · loops
 * Interactions: glasses on hover
 * Deps:  npm i gsap @gsap/react
 *
 * Sizing: the SVG fills its container by default - wrap it in a sized element,
 * or pass className / style (e.g. style={{ width: 240, height: 240 }}).
 * overflow:visible lets motion extend past the frame (matches the editor).
 */
export default function Nadir({ className, style, onClick }: NadirProps = {}) {
  const root = useRef<SVGSVGElement>(null);

  useGSAP(() => {
    const cleanups: (() => void)[] = [];
    
    // shared pointer bus - one listener, per-frame followers
    const __ptr = { x: 0, y: 0, dirty: false, seen: false };
    const __followers: (() => void)[] = [];
    const __ptrMove = (e: MouseEvent) => { __ptr.x = e.clientX; __ptr.y = e.clientY; __ptr.dirty = true; __ptr.seen = true; };
    const __ptrTick = () => { if (!__ptr.dirty) return; __ptr.dirty = false; for (const f of __followers) f(); };
    window.addEventListener("mousemove", __ptrMove);
    gsap.ticker.add(__ptrTick);
    cleanups.push(() => { window.removeEventListener("mousemove", __ptrMove); gsap.ticker.remove(__ptrTick); });
    
    // path-utbq2eq · breathe
    gsap.set("#path-utbq2eq", { svgOrigin: "252.14999389648438 295.34500885009766" });
    gsap.to("#path-utbq2eq", { scale: "+=0.06", duration: 2, ease: "sine.inOut", yoyo: true, repeat: -1 });
    
    // group · float
    gsap.to("#group", { y: "-=8", duration: 2.1, ease: "sine.inOut", yoyo: true, repeat: -1 });
    
    // group-2 · followMouse
    {
      const __el = root.current?.querySelector("#group-2") as SVGGraphicsElement | null;
      const __ly = (root.current?.querySelector("#group-2-c") as SVGGraphicsElement | null) ?? __el;
      if (__el && __ly) {
        const __xTo = gsap.quickTo(__ly, "x", { duration: 0.4, ease: "power3" });
        const __yTo = gsap.quickTo(__ly, "y", { duration: 0.4, ease: "power3" });
        __followers.push(() => {
          const __r = __el.getBoundingClientRect(); const __cx = __r.left + __r.width / 2, __cy = __r.top + __r.height / 2;
          const __ox = Number(gsap.getProperty(__ly, "x")) || 0, __oy = Number(gsap.getProperty(__ly, "y")) || 0;
          const __pm = (__ly.parentNode as SVGGraphicsElement | null)?.getScreenCTM?.();
          const __sox = __pm ? __pm.a * __ox + __pm.c * __oy : __ox, __soy = __pm ? __pm.b * __ox + __pm.d * __oy : __oy;
          const dx = __ptr.x - (__cx - __sox), dy = __ptr.y - (__cy - __soy);
          const d = Math.hypot(dx, dy) || 1, c = (Math.min(d, 30) / d) * 0.18;
          const __sx = dx * c, __sy = dy * c;
          const __p = (__ly.parentNode as SVGGraphicsElement | null)?.getScreenCTM?.();
          const __det = __p ? __p.a * __p.d - __p.b * __p.c : 0;
          const __vx = __det ? (__p!.d * __sx - __p!.c * __sy) / __det : __sx;
          const __vy = __det ? (__p!.a * __sy - __p!.b * __sx) / __det : __sy;
          __xTo(__vx); __yTo(__vy);
        });
      }
    }
    
    // group-3 · followMouse
    {
      const __el = root.current?.querySelector("#group-3") as SVGGraphicsElement | null;
      const __ly = (root.current?.querySelector("#group-3-c") as SVGGraphicsElement | null) ?? __el;
      if (__el && __ly) {
        const __xTo = gsap.quickTo(__ly, "x", { duration: 0.4, ease: "power3" });
        const __yTo = gsap.quickTo(__ly, "y", { duration: 0.4, ease: "power3" });
        __followers.push(() => {
          const __r = __el.getBoundingClientRect(); const __cx = __r.left + __r.width / 2, __cy = __r.top + __r.height / 2;
          const __ox = Number(gsap.getProperty(__ly, "x")) || 0, __oy = Number(gsap.getProperty(__ly, "y")) || 0;
          const __pm = (__ly.parentNode as SVGGraphicsElement | null)?.getScreenCTM?.();
          const __sox = __pm ? __pm.a * __ox + __pm.c * __oy : __ox, __soy = __pm ? __pm.b * __ox + __pm.d * __oy : __oy;
          const dx = __ptr.x - (__cx - __sox), dy = __ptr.y - (__cy - __soy);
          const d = Math.hypot(dx, dy) || 1, c = (Math.min(d, 30) / d) * 0.18;
          const __sx = dx * c, __sy = dy * c;
          const __p = (__ly.parentNode as SVGGraphicsElement | null)?.getScreenCTM?.();
          const __det = __p ? __p.a * __p.d - __p.b * __p.c : 0;
          const __vx = __det ? (__p!.d * __sx - __p!.c * __sy) / __det : __sx;
          const __vy = __det ? (__p!.a * __sy - __p!.b * __sx) / __det : __sy;
          __xTo(__vx); __yTo(__vy);
        });
      }
    }
    
    // path-mzmgqf1 · breathe
    gsap.set("#path-mzmgqf1", { svgOrigin: "252.06198120117188 295.3429412841797" });
    gsap.to("#path-mzmgqf1", { scale: "+=0.06", duration: 2, ease: "sine.inOut", yoyo: true, repeat: -1 });
    
    // path-lmotihb · node actions (runAway)
    {
      const __el = root.current?.querySelector("#path-lmotihb") as SVGPathElement | null;
      if (__el) {
        const __slots = [[8,9,10]];
        const __aidx = [9];
        const __afall = [[252.08,6.94]];
        const __TOTAL = 13;
        const __ns: { x: number; y: number }[] = [];
        const __rd = (n: number) => Math.round(n * 100) / 100;
        interface __Base { head: string[]; pairs: [number, number][]; on: boolean[]; closed: boolean; tail: string; slots: number[][]; aidx: number[] }
        let __last: string | null = null;
        let __base: __Base | null = null;
        const __parse = (pd: string): __Base | null => {
          if (/[AaHhVv]/.test(pd)) return null;
          const toks = pd.match(/-?(?:\d+\.?\d*|\.\d+)(?:e[-+]?\d+)?|[a-zA-Z]/g) || [];
          const need: Record<string, number> = { M: 1, L: 1, T: 1, Q: 2, S: 2, C: 3 };
          const head: string[] = []; const pairs: [number, number][] = []; const on: boolean[] = [];
          let cur = ""; let seg = 1; let seen = 0;
          for (let i = 0; i < toks.length; i++) {
            if (toks[i].length === 1 && /[a-zA-Z]/.test(toks[i])) {
              cur += (cur ? " " : "") + toks[i];
              seg = need[toks[i].toUpperCase()] ?? 1; seen = 0;
              continue;
            }
            const x = Number(toks[i]), y = Number(toks[++i]);
            if (isNaN(x) || isNaN(y)) return null;
            head.push(cur ? cur + " " : ""); pairs.push([x, y]); cur = "";
            seen++; on.push(seen === seg); if (seen === seg) seen = 0;
          }
          const b: __Base = { head, pairs, on, closed: /[Zz]/.test(pd), tail: cur, slots: [], aidx: [] };
          if (pairs.length === __TOTAL) { b.slots = __slots; b.aidx = __aidx; return b; }
          const onIdx = on.map((v, i) => v ? i : -1).filter(i => i >= 0);
          if (!onIdx.length) return null;
          for (let k = 0; k < __afall.length; k++) {
            let j = onIdx[0];
            for (const i of onIdx) {
              if (Math.hypot(pairs[i][0] - __afall[k][0], pairs[i][1] - __afall[k][1]) < Math.hypot(pairs[j][0] - __afall[k][0], pairs[j][1] - __afall[k][1])) j = i;
            }
            const set = new Set<number>([j]);
            if (j > 0 && !on[j - 1]) set.add(j - 1);
            if (j + 1 < pairs.length && !on[j + 1]) set.add(j + 1);
            const f = onIdx[0], l = onIdx[onIdx.length - 1];
            if (b.closed && j === f) { set.add(l); if (l > 0 && !on[l - 1]) set.add(l - 1); }
            if (b.closed && j === l) { set.add(f); if (f + 1 < pairs.length && !on[f + 1]) set.add(f + 1); }
            b.slots.push([...set]); b.aidx.push(j);
          }
          return b;
        };
        const __sync = () => {
          const cur = __el.getAttribute("d") || "";
          if (cur !== __last) { __base = __parse(cur); __last = cur; }
          return __base;
        };
        const __apply = () => {
          if (__ns.every(n => Math.abs(n.x) < 0.01 && Math.abs(n.y) < 0.01)) return;
          const b = __sync();
          if (!b) return;
          const __ox = b.pairs.map(() => 0), __oy = b.pairs.map(() => 0);
          for (let k = 0; k < __ns.length; k++) for (const s of b.slots[k]) { __ox[s] += __ns[k].x; __oy[s] += __ns[k].y; }
          let __d = "";
          for (let i = 0; i < b.pairs.length; i++) __d += b.head[i] + __rd(b.pairs[i][0] + __ox[i]) + " " + __rd(b.pairs[i][1] + __oy[i]) + " ";
          __d = (__d + b.tail).trim();
          __el.setAttribute("d", __d);
          __last = __d;
        };
        gsap.ticker.add(__apply);
        cleanups.push(() => gsap.ticker.remove(__apply));
        const __n0 = { x: 0, y: 0 }; __ns.push(__n0);
        const __xTo0 = gsap.quickTo(__n0, "x", { duration: 0.35, ease: "power3" });
        const __yTo0 = gsap.quickTo(__n0, "y", { duration: 0.35, ease: "power3" });
        const __move0 = () => {
          const __m = __el.getScreenCTM(); if (!__m) return;
          const __b0 = __sync();
          const __a0 = __b0 ? __b0.pairs[__b0.aidx[0]] : __afall[0];
          const __ap = __el.ownerSVGElement!.createSVGPoint(); __ap.x = __a0[0]; __ap.y = __a0[1];
          const __c = __ap.matrixTransform(__m);
          const dx = __c.x - __ptr.x, dy = __c.y - __ptr.y;
          const dd = Math.hypot(dx, dy) || 1, f = dd < 80 ? (80 - dd) / 80 : 0;
          const __sx = (dx / dd) * 20 * f, __sy = (dy / dd) * 20 * f;
          const __det = __m.a * __m.d - __m.b * __m.c;
          __xTo0(__det ? (__m.d * __sx - __m.c * __sy) / __det : __sx);
          __yTo0(__det ? (__m.a * __sy - __m.b * __sx) / __det : __sy);
        };
        __followers.push(__move0);
      }
    }
    
    // path-utbq2eq · node actions (drag, drag, drag, drag)
    {
      const __el = root.current?.querySelector("#path-utbq2eq") as SVGPathElement | null;
      if (__el) {
        const __slots = [[0,1,11,12],[2,3,4],[5,6,7],[8,9,10]];
        const __aidx = [0,3,6,9];
        const __afall = [[351.705,315.242],[252.062,399.501],[152.419,315.242],[252.062,184.461]];
        const __TOTAL = 13;
        const __ns: { x: number; y: number }[] = [];
        const __rd = (n: number) => Math.round(n * 100) / 100;
        interface __Base { head: string[]; pairs: [number, number][]; on: boolean[]; closed: boolean; tail: string; slots: number[][]; aidx: number[] }
        let __last: string | null = null;
        let __base: __Base | null = null;
        const __parse = (pd: string): __Base | null => {
          if (/[AaHhVv]/.test(pd)) return null;
          const toks = pd.match(/-?(?:\d+\.?\d*|\.\d+)(?:e[-+]?\d+)?|[a-zA-Z]/g) || [];
          const need: Record<string, number> = { M: 1, L: 1, T: 1, Q: 2, S: 2, C: 3 };
          const head: string[] = []; const pairs: [number, number][] = []; const on: boolean[] = [];
          let cur = ""; let seg = 1; let seen = 0;
          for (let i = 0; i < toks.length; i++) {
            if (toks[i].length === 1 && /[a-zA-Z]/.test(toks[i])) {
              cur += (cur ? " " : "") + toks[i];
              seg = need[toks[i].toUpperCase()] ?? 1; seen = 0;
              continue;
            }
            const x = Number(toks[i]), y = Number(toks[++i]);
            if (isNaN(x) || isNaN(y)) return null;
            head.push(cur ? cur + " " : ""); pairs.push([x, y]); cur = "";
            seen++; on.push(seen === seg); if (seen === seg) seen = 0;
          }
          const b: __Base = { head, pairs, on, closed: /[Zz]/.test(pd), tail: cur, slots: [], aidx: [] };
          if (pairs.length === __TOTAL) { b.slots = __slots; b.aidx = __aidx; return b; }
          const onIdx = on.map((v, i) => v ? i : -1).filter(i => i >= 0);
          if (!onIdx.length) return null;
          for (let k = 0; k < __afall.length; k++) {
            let j = onIdx[0];
            for (const i of onIdx) {
              if (Math.hypot(pairs[i][0] - __afall[k][0], pairs[i][1] - __afall[k][1]) < Math.hypot(pairs[j][0] - __afall[k][0], pairs[j][1] - __afall[k][1])) j = i;
            }
            const set = new Set<number>([j]);
            if (j > 0 && !on[j - 1]) set.add(j - 1);
            if (j + 1 < pairs.length && !on[j + 1]) set.add(j + 1);
            const f = onIdx[0], l = onIdx[onIdx.length - 1];
            if (b.closed && j === f) { set.add(l); if (l > 0 && !on[l - 1]) set.add(l - 1); }
            if (b.closed && j === l) { set.add(f); if (f + 1 < pairs.length && !on[f + 1]) set.add(f + 1); }
            b.slots.push([...set]); b.aidx.push(j);
          }
          return b;
        };
        const __sync = () => {
          const cur = __el.getAttribute("d") || "";
          if (cur !== __last) { __base = __parse(cur); __last = cur; }
          return __base;
        };
        const __apply = () => {
          if (__ns.every(n => Math.abs(n.x) < 0.01 && Math.abs(n.y) < 0.01)) return;
          const b = __sync();
          if (!b) return;
          const __ox = b.pairs.map(() => 0), __oy = b.pairs.map(() => 0);
          for (let k = 0; k < __ns.length; k++) for (const s of b.slots[k]) { __ox[s] += __ns[k].x; __oy[s] += __ns[k].y; }
          let __d = "";
          for (let i = 0; i < b.pairs.length; i++) __d += b.head[i] + __rd(b.pairs[i][0] + __ox[i]) + " " + __rd(b.pairs[i][1] + __oy[i]) + " ";
          __d = (__d + b.tail).trim();
          __el.setAttribute("d", __d);
          __last = __d;
        };
        gsap.ticker.add(__apply);
        cleanups.push(() => gsap.ticker.remove(__apply));
        const __n0 = { x: 0, y: 0 }; __ns.push(__n0);
        {
          let __dg0 = false, __px0 = 0, __py0 = 0, __bx0 = 0, __by0 = 0;
          let __vx0 = 0, __vy0 = 0, __lx0 = 0, __ly0 = 0, __lt0 = 0;
          const __down0 = (e: PointerEvent) => {
            const __m = __el.getScreenCTM(); if (!__m) return;
            const __b = __sync();
            const __a = __b ? __b.pairs[__b.aidx[0]] : __afall[0];
            const __ap = __el.ownerSVGElement!.createSVGPoint(); __ap.x = __a[0] + __n0.x; __ap.y = __a[1] + __n0.y;
            const __c = __ap.matrixTransform(__m);
            if (Math.hypot(e.clientX - __c.x, e.clientY - __c.y) > 18) return;
            __dg0 = true; __px0 = e.clientX; __py0 = e.clientY; __bx0 = __n0.x; __by0 = __n0.y;
            __lx0 = __n0.x; __ly0 = __n0.y; __lt0 = performance.now(); __vx0 = __vy0 = 0;
            gsap.killTweensOf(__n0); e.preventDefault();
            __el.dispatchEvent(new CustomEvent("stew:grab", { bubbles: true }));
          };
          const __mv0 = (e: PointerEvent) => {
            if (!__dg0) return;
            const __m = __el.getScreenCTM(); if (!__m) return;
            const __det = __m.a * __m.d - __m.b * __m.c, dx = e.clientX - __px0, dy = e.clientY - __py0;
            __n0.x = __bx0 + (__det ? (__m.d * dx - __m.c * dy) / __det : dx);
            __n0.y = __by0 + (__det ? (__m.a * dy - __m.b * dx) / __det : dy);
            const __nw = performance.now(), __dt = Math.max(__nw - __lt0, 1);
            __vx0 = ((__n0.x - __lx0) / __dt) * 900 + __vx0 * 0.1;
            __vy0 = ((__n0.y - __ly0) / __dt) * 900 + __vy0 * 0.1;
            __lx0 = __n0.x; __ly0 = __n0.y; __lt0 = __nw;
          };
          const __up0 = () => {
            if (!__dg0) return; __dg0 = false;
            __el.dispatchEvent(new CustomEvent("stew:release", { bubbles: true }));
            if (Math.hypot(__vx0, __vy0) > 300) __el.dispatchEvent(new CustomEvent("stew:throw", { bubbles: true }));
            const __tl0 = gsap.timeline();
            const __cap0 = 136;
            const __gx0 = Math.max(-__cap0, Math.min(__cap0, __vx0 * 0.072));
            const __gy0 = Math.max(-__cap0, Math.min(__cap0, __vy0 * 0.072));
            if (Math.abs(__gx0) > 1 || Math.abs(__gy0) > 1) __tl0.to(__n0, { x: "+=" + __gx0, y: "+=" + __gy0, duration: 0.42, ease: "power2.out" });
            __tl0.to(__n0, { x: 0, y: 0, duration: 1.37, ease: "elastic.out(1, 0.3)" });
          };
          __el.ownerSVGElement!.addEventListener("pointerdown", __down0);
          window.addEventListener("pointermove", __mv0);
          window.addEventListener("pointerup", __up0);
          cleanups.push(() => { __el.ownerSVGElement!.removeEventListener("pointerdown", __down0); window.removeEventListener("pointermove", __mv0); window.removeEventListener("pointerup", __up0); });
        }
        const __n1 = { x: 0, y: 0 }; __ns.push(__n1);
        {
          let __dg1 = false, __px1 = 0, __py1 = 0, __bx1 = 0, __by1 = 0;
          let __vx1 = 0, __vy1 = 0, __lx1 = 0, __ly1 = 0, __lt1 = 0;
          const __down1 = (e: PointerEvent) => {
            const __m = __el.getScreenCTM(); if (!__m) return;
            const __b = __sync();
            const __a = __b ? __b.pairs[__b.aidx[1]] : __afall[1];
            const __ap = __el.ownerSVGElement!.createSVGPoint(); __ap.x = __a[0] + __n1.x; __ap.y = __a[1] + __n1.y;
            const __c = __ap.matrixTransform(__m);
            if (Math.hypot(e.clientX - __c.x, e.clientY - __c.y) > 18) return;
            __dg1 = true; __px1 = e.clientX; __py1 = e.clientY; __bx1 = __n1.x; __by1 = __n1.y;
            __lx1 = __n1.x; __ly1 = __n1.y; __lt1 = performance.now(); __vx1 = __vy1 = 0;
            gsap.killTweensOf(__n1); e.preventDefault();
            __el.dispatchEvent(new CustomEvent("stew:grab", { bubbles: true }));
          };
          const __mv1 = (e: PointerEvent) => {
            if (!__dg1) return;
            const __m = __el.getScreenCTM(); if (!__m) return;
            const __det = __m.a * __m.d - __m.b * __m.c, dx = e.clientX - __px1, dy = e.clientY - __py1;
            __n1.x = __bx1 + (__det ? (__m.d * dx - __m.c * dy) / __det : dx);
            __n1.y = __by1 + (__det ? (__m.a * dy - __m.b * dx) / __det : dy);
            const __nw = performance.now(), __dt = Math.max(__nw - __lt1, 1);
            __vx1 = ((__n1.x - __lx1) / __dt) * 900 + __vx1 * 0.1;
            __vy1 = ((__n1.y - __ly1) / __dt) * 900 + __vy1 * 0.1;
            __lx1 = __n1.x; __ly1 = __n1.y; __lt1 = __nw;
          };
          const __up1 = () => {
            if (!__dg1) return; __dg1 = false;
            __el.dispatchEvent(new CustomEvent("stew:release", { bubbles: true }));
            if (Math.hypot(__vx1, __vy1) > 300) __el.dispatchEvent(new CustomEvent("stew:throw", { bubbles: true }));
            const __tl1 = gsap.timeline();
            const __cap1 = 136;
            const __gx1 = Math.max(-__cap1, Math.min(__cap1, __vx1 * 0.072));
            const __gy1 = Math.max(-__cap1, Math.min(__cap1, __vy1 * 0.072));
            if (Math.abs(__gx1) > 1 || Math.abs(__gy1) > 1) __tl1.to(__n1, { x: "+=" + __gx1, y: "+=" + __gy1, duration: 0.42, ease: "power2.out" });
            __tl1.to(__n1, { x: 0, y: 0, duration: 1.37, ease: "elastic.out(1, 0.3)" });
          };
          __el.ownerSVGElement!.addEventListener("pointerdown", __down1);
          window.addEventListener("pointermove", __mv1);
          window.addEventListener("pointerup", __up1);
          cleanups.push(() => { __el.ownerSVGElement!.removeEventListener("pointerdown", __down1); window.removeEventListener("pointermove", __mv1); window.removeEventListener("pointerup", __up1); });
        }
        const __n2 = { x: 0, y: 0 }; __ns.push(__n2);
        {
          let __dg2 = false, __px2 = 0, __py2 = 0, __bx2 = 0, __by2 = 0;
          let __vx2 = 0, __vy2 = 0, __lx2 = 0, __ly2 = 0, __lt2 = 0;
          const __down2 = (e: PointerEvent) => {
            const __m = __el.getScreenCTM(); if (!__m) return;
            const __b = __sync();
            const __a = __b ? __b.pairs[__b.aidx[2]] : __afall[2];
            const __ap = __el.ownerSVGElement!.createSVGPoint(); __ap.x = __a[0] + __n2.x; __ap.y = __a[1] + __n2.y;
            const __c = __ap.matrixTransform(__m);
            if (Math.hypot(e.clientX - __c.x, e.clientY - __c.y) > 18) return;
            __dg2 = true; __px2 = e.clientX; __py2 = e.clientY; __bx2 = __n2.x; __by2 = __n2.y;
            __lx2 = __n2.x; __ly2 = __n2.y; __lt2 = performance.now(); __vx2 = __vy2 = 0;
            gsap.killTweensOf(__n2); e.preventDefault();
            __el.dispatchEvent(new CustomEvent("stew:grab", { bubbles: true }));
          };
          const __mv2 = (e: PointerEvent) => {
            if (!__dg2) return;
            const __m = __el.getScreenCTM(); if (!__m) return;
            const __det = __m.a * __m.d - __m.b * __m.c, dx = e.clientX - __px2, dy = e.clientY - __py2;
            __n2.x = __bx2 + (__det ? (__m.d * dx - __m.c * dy) / __det : dx);
            __n2.y = __by2 + (__det ? (__m.a * dy - __m.b * dx) / __det : dy);
            const __nw = performance.now(), __dt = Math.max(__nw - __lt2, 1);
            __vx2 = ((__n2.x - __lx2) / __dt) * 900 + __vx2 * 0.1;
            __vy2 = ((__n2.y - __ly2) / __dt) * 900 + __vy2 * 0.1;
            __lx2 = __n2.x; __ly2 = __n2.y; __lt2 = __nw;
          };
          const __up2 = () => {
            if (!__dg2) return; __dg2 = false;
            __el.dispatchEvent(new CustomEvent("stew:release", { bubbles: true }));
            if (Math.hypot(__vx2, __vy2) > 300) __el.dispatchEvent(new CustomEvent("stew:throw", { bubbles: true }));
            const __tl2 = gsap.timeline();
            const __cap2 = 136;
            const __gx2 = Math.max(-__cap2, Math.min(__cap2, __vx2 * 0.072));
            const __gy2 = Math.max(-__cap2, Math.min(__cap2, __vy2 * 0.072));
            if (Math.abs(__gx2) > 1 || Math.abs(__gy2) > 1) __tl2.to(__n2, { x: "+=" + __gx2, y: "+=" + __gy2, duration: 0.42, ease: "power2.out" });
            __tl2.to(__n2, { x: 0, y: 0, duration: 1.37, ease: "elastic.out(1, 0.3)" });
          };
          __el.ownerSVGElement!.addEventListener("pointerdown", __down2);
          window.addEventListener("pointermove", __mv2);
          window.addEventListener("pointerup", __up2);
          cleanups.push(() => { __el.ownerSVGElement!.removeEventListener("pointerdown", __down2); window.removeEventListener("pointermove", __mv2); window.removeEventListener("pointerup", __up2); });
        }
        const __n3 = { x: 0, y: 0 }; __ns.push(__n3);
        {
          let __dg3 = false, __px3 = 0, __py3 = 0, __bx3 = 0, __by3 = 0;
          let __vx3 = 0, __vy3 = 0, __lx3 = 0, __ly3 = 0, __lt3 = 0;
          const __down3 = (e: PointerEvent) => {
            const __m = __el.getScreenCTM(); if (!__m) return;
            const __b = __sync();
            const __a = __b ? __b.pairs[__b.aidx[3]] : __afall[3];
            const __ap = __el.ownerSVGElement!.createSVGPoint(); __ap.x = __a[0] + __n3.x; __ap.y = __a[1] + __n3.y;
            const __c = __ap.matrixTransform(__m);
            if (Math.hypot(e.clientX - __c.x, e.clientY - __c.y) > 18) return;
            __dg3 = true; __px3 = e.clientX; __py3 = e.clientY; __bx3 = __n3.x; __by3 = __n3.y;
            __lx3 = __n3.x; __ly3 = __n3.y; __lt3 = performance.now(); __vx3 = __vy3 = 0;
            gsap.killTweensOf(__n3); e.preventDefault();
            __el.dispatchEvent(new CustomEvent("stew:grab", { bubbles: true }));
          };
          const __mv3 = (e: PointerEvent) => {
            if (!__dg3) return;
            const __m = __el.getScreenCTM(); if (!__m) return;
            const __det = __m.a * __m.d - __m.b * __m.c, dx = e.clientX - __px3, dy = e.clientY - __py3;
            __n3.x = __bx3 + (__det ? (__m.d * dx - __m.c * dy) / __det : dx);
            __n3.y = __by3 + (__det ? (__m.a * dy - __m.b * dx) / __det : dy);
            const __nw = performance.now(), __dt = Math.max(__nw - __lt3, 1);
            __vx3 = ((__n3.x - __lx3) / __dt) * 900 + __vx3 * 0.1;
            __vy3 = ((__n3.y - __ly3) / __dt) * 900 + __vy3 * 0.1;
            __lx3 = __n3.x; __ly3 = __n3.y; __lt3 = __nw;
          };
          const __up3 = () => {
            if (!__dg3) return; __dg3 = false;
            __el.dispatchEvent(new CustomEvent("stew:release", { bubbles: true }));
            if (Math.hypot(__vx3, __vy3) > 300) __el.dispatchEvent(new CustomEvent("stew:throw", { bubbles: true }));
            const __tl3 = gsap.timeline();
            const __cap3 = 136;
            const __gx3 = Math.max(-__cap3, Math.min(__cap3, __vx3 * 0.072));
            const __gy3 = Math.max(-__cap3, Math.min(__cap3, __vy3 * 0.072));
            if (Math.abs(__gx3) > 1 || Math.abs(__gy3) > 1) __tl3.to(__n3, { x: "+=" + __gx3, y: "+=" + __gy3, duration: 0.42, ease: "power2.out" });
            __tl3.to(__n3, { x: 0, y: 0, duration: 1.37, ease: "elastic.out(1, 0.3)" });
          };
          __el.ownerSVGElement!.addEventListener("pointerdown", __down3);
          window.addEventListener("pointermove", __mv3);
          window.addEventListener("pointerup", __up3);
          cleanups.push(() => { __el.ownerSVGElement!.removeEventListener("pointerdown", __down3); window.removeEventListener("pointermove", __mv3); window.removeEventListener("pointerup", __up3); });
        }
      }
    }
    
    // glasses · plays on hover of the whole component, plays back when released
    const glassesTl = (() => {
      const tl = gsap.timeline({ paused: true });
      tl.to({}, { duration: 3 }, 0); // hold to the full length
      
      // path-rt5oxqg · pivot - stepped transform-origin (smoothOrigin keeps the tumble continuous)
      gsap.set("#path-rt5oxqg-i", { transformOrigin: "50% 50%", smoothOrigin: true });
      tl.set("#path-rt5oxqg-i", { transformOrigin: "50% 50%", smoothOrigin: true }, 0);
      
      // path-w4m1znv · pivot - stepped transform-origin (smoothOrigin keeps the tumble continuous)
      gsap.set("#path-w4m1znv-i", { transformOrigin: "50% 50%", smoothOrigin: true });
      tl.set("#path-w4m1znv-i", { transformOrigin: "50% 50%", smoothOrigin: true }, 0);
      
      // path-5ir0euf · scaleX
      gsap.set("#path-5ir0euf-i", { scaleX: 1, transformOrigin: "50.000002574088974% 0.000001709338829108372%" });
      tl.to("#path-5ir0euf-i", { scaleX: 1.046, duration: 0.401, ease: "power1.inOut" }, 0);
      
      // path-5ir0euf · scaleY
      gsap.set("#path-5ir0euf-i", { scaleY: 1, transformOrigin: "50.000002574088974% 0.000001709338829108372%" });
      tl.to("#path-5ir0euf-i", { scaleY: 0.107, duration: 0.401, ease: "power1.inOut" }, 0);
      
      // path-rysppx4 · scaleX
      gsap.set("#path-rysppx4-i", { scaleX: 1, transformOrigin: "49.99998519419246% 0.000001709338829108372%" });
      tl.to("#path-rysppx4-i", { scaleX: 0.944, duration: 0.401, ease: "power1.inOut" }, 0);
      
      // path-rysppx4 · scaleY
      gsap.set("#path-rysppx4-i", { scaleY: 1, transformOrigin: "49.99998519419246% 0.000001709338829108372%" });
      tl.to("#path-rysppx4-i", { scaleY: 0.166, duration: 0.401, ease: "power1.inOut" }, 0);
      
      // path-x7pz8y4 · x
      gsap.set("#path-x7pz8y4-i", { x: 0, transformOrigin: "49.9999885664954% 49.999997863399145%" });
      tl.to("#path-x7pz8y4-i", { x: 0, duration: 0.401, ease: "power1.inOut" }, 0);
      tl.to("#path-x7pz8y4-i", { x: 15.43, duration: 0.207, ease: "power1.inOut" }, 0.401);
      
      // path-x7pz8y4 · y
      gsap.set("#path-x7pz8y4-i", { y: 0, transformOrigin: "49.9999885664954% 49.999997863399145%" });
      tl.to("#path-x7pz8y4-i", { y: 0, duration: 0.401, ease: "power1.inOut" }, 0);
      tl.to("#path-x7pz8y4-i", { y: -12.25, duration: 0.207, ease: "power1.inOut" }, 0.401);
      
      // path-x7pz8y4 · rotate
      gsap.set("#path-x7pz8y4-i", { rotation: 0, transformOrigin: "49.9999885664954% 49.999997863399145%" });
      tl.to("#path-x7pz8y4-i", { rotation: 0, duration: 0.401, ease: "power1.inOut" }, 0);
      tl.to("#path-x7pz8y4-i", { rotation: 22.9, duration: 0.207, ease: "power1.inOut" }, 0.401);
      
      // path-0acus0d · x
      gsap.set("#path-0acus0d-i", { x: 0, transformOrigin: "49.999995733308175% 49.99997908167378%" });
      tl.to("#path-0acus0d-i", { x: 0, duration: 0.401, ease: "power1.inOut" }, 0);
      tl.to("#path-0acus0d-i", { x: -4.19, duration: 0.207, ease: "power1.inOut" }, 0.401);
      
      // path-0acus0d · y
      gsap.set("#path-0acus0d-i", { y: 0, transformOrigin: "49.999995733308175% 49.99997908167378%" });
      tl.to("#path-0acus0d-i", { y: 0, duration: 0.401, ease: "power1.inOut" }, 0);
      tl.to("#path-0acus0d-i", { y: -6.08, duration: 0.207, ease: "power1.inOut" }, 0.401);
      
      // circle-5vhyb1a · scaleX
      gsap.set("#circle-5vhyb1a-i", { scaleX: 1, transformOrigin: "50% 50%" });
      tl.to("#circle-5vhyb1a-i", { scaleX: 1, duration: 0.401, ease: "power1.inOut" }, 0);
      tl.to("#circle-5vhyb1a-i", { scaleX: 1.765, duration: 0.207, ease: "power1.inOut" }, 0.401);
      
      // circle-5vhyb1a · scaleY
      gsap.set("#circle-5vhyb1a-i", { scaleY: 1, transformOrigin: "50% 50%" });
      tl.to("#circle-5vhyb1a-i", { scaleY: 1, duration: 0.401, ease: "power1.inOut" }, 0);
      tl.to("#circle-5vhyb1a-i", { scaleY: 1.765, duration: 0.207, ease: "power1.inOut" }, 0.401);
      
      // path-igkge07 · scaleX
      gsap.set("#path-igkge07-i", { scaleX: 1, transformOrigin: "50% 50%" });
      tl.to("#path-igkge07-i", { scaleX: 1, duration: 0.401, ease: "power1.inOut" }, 0);
      tl.to("#path-igkge07-i", { scaleX: 1.765, duration: 0.207, ease: "power1.inOut" }, 0.401);
      
      // path-igkge07 · scaleY
      gsap.set("#path-igkge07-i", { scaleY: 1, transformOrigin: "50% 50%" });
      tl.to("#path-igkge07-i", { scaleY: 1, duration: 0.401, ease: "power1.inOut" }, 0);
      tl.to("#path-igkge07-i", { scaleY: 1.765, duration: 0.207, ease: "power1.inOut" }, 0.401);
      
      // circle-3hwqdxj · scaleX
      gsap.set("#circle-3hwqdxj-i", { scaleX: 1, transformOrigin: "50% 50%" });
      tl.to("#circle-3hwqdxj-i", { scaleX: 1, duration: 0.401, ease: "power1.inOut" }, 0);
      tl.to("#circle-3hwqdxj-i", { scaleX: 1.765, duration: 0.207, ease: "power1.inOut" }, 0.401);
      
      // circle-3hwqdxj · scaleY
      gsap.set("#circle-3hwqdxj-i", { scaleY: 1, transformOrigin: "50% 50%" });
      tl.to("#circle-3hwqdxj-i", { scaleY: 1, duration: 0.401, ease: "power1.inOut" }, 0);
      tl.to("#circle-3hwqdxj-i", { scaleY: 1.765, duration: 0.207, ease: "power1.inOut" }, 0.401);
      
      // path-k4vqxm3 · scaleX
      gsap.set("#path-k4vqxm3-i", { scaleX: 1, transformOrigin: "50% 50%" });
      tl.to("#path-k4vqxm3-i", { scaleX: 1, duration: 0.401, ease: "power1.inOut" }, 0);
      tl.to("#path-k4vqxm3-i", { scaleX: 1.765, duration: 0.207, ease: "power1.inOut" }, 0.401);
      
      // path-k4vqxm3 · scaleY
      gsap.set("#path-k4vqxm3-i", { scaleY: 1, transformOrigin: "50% 50%" });
      tl.to("#path-k4vqxm3-i", { scaleY: 1, duration: 0.401, ease: "power1.inOut" }, 0);
      tl.to("#path-k4vqxm3-i", { scaleY: 1.765, duration: 0.207, ease: "power1.inOut" }, 0.401);
      
      // g-f2upu46 · x
      gsap.set("#g-f2upu46-i", { x: 0, transformOrigin: "50% 50%" });
      tl.to("#g-f2upu46-i", { x: 0, duration: 0.401, ease: "power1.inOut" }, 0);
      
      // g-f2upu46 · y
      gsap.set("#g-f2upu46-i", { y: 0, transformOrigin: "50% 50%" });
      tl.to("#g-f2upu46-i", { y: 0, duration: 0.401, ease: "power1.inOut" }, 0);
      
      // path-rt5oxqg · x
      gsap.set("#path-rt5oxqg-i", { x: 0 });
      tl.to("#path-rt5oxqg-i", { x: 10.38, duration: 0.608, ease: "power1.inOut" }, 0);
      
      // path-rt5oxqg · y
      gsap.set("#path-rt5oxqg-i", { y: 0 });
      tl.to("#path-rt5oxqg-i", { y: 11.84, duration: 0.608, ease: "power1.inOut" }, 0);
      
      // path-rt5oxqg · scaleX
      gsap.set("#path-rt5oxqg-i", { scaleX: 1 });
      tl.to("#path-rt5oxqg-i", { scaleX: 0.698, duration: 0.608, ease: "power1.inOut" }, 0);
      
      // path-rt5oxqg · scaleY
      gsap.set("#path-rt5oxqg-i", { scaleY: 1 });
      tl.to("#path-rt5oxqg-i", { scaleY: 0.828, duration: 0.608, ease: "power1.inOut" }, 0);
      
      // path-w4m1znv · x
      gsap.set("#path-w4m1znv-i", { x: 0 });
      tl.to("#path-w4m1znv-i", { x: -11.97, duration: 0.608, ease: "power1.inOut" }, 0);
      
      // path-w4m1znv · y
      gsap.set("#path-w4m1znv-i", { y: 0 });
      tl.to("#path-w4m1znv-i", { y: 12.44, duration: 0.608, ease: "power1.inOut" }, 0);
      
      // path-w4m1znv · scaleX
      gsap.set("#path-w4m1znv-i", { scaleX: 1 });
      tl.to("#path-w4m1znv-i", { scaleX: 0.698, duration: 0.608, ease: "power1.inOut" }, 0);
      
      // path-w4m1znv · scaleY
      gsap.set("#path-w4m1znv-i", { scaleY: 1 });
      tl.to("#path-w4m1znv-i", { scaleY: 0.828, duration: 0.608, ease: "power1.inOut" }, 0);
      return tl;
    })();
    {
      const host = root.current?.parentElement;
      const wrap = host && (host.tagName === "BUTTON" || host.tagName === "A" || host.tagName === "LABEL") ? host : root.current;
      const targets: (HTMLElement | SVGElement)[] = wrap ? [wrap] : [];
      const onEnter = () => { glassesTl.play(); };
      const onLeave = () => { glassesTl.reverse(); };
      targets.forEach((t) => { t.addEventListener("mouseenter", onEnter); t.addEventListener("mouseleave", onLeave); });
      cleanups.push(() => targets.forEach((t) => { t.removeEventListener("mouseenter", onEnter); t.removeEventListener("mouseleave", onLeave); }));
    }
    return () => cleanups.forEach((fn) => fn());
  }, { scope: root });

  return (
    <svg ref={root} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 504.123 504.123" onClick={onClick} className={className} style={{ overflow: "visible", ...style }}>
      <g id="g-f2upu46-i">
        <g id="g-f2upu46-a">
          <g id="g-f2upu46">
            <g id="g-tzv4qw6">
              <path d="M228.218,361.913c0,19.503-15.817,124.668-35.336,124.668c-19.495,0-35.304-105.173-35.304-124.668 c0-19.495,15.817-35.32,35.304-35.32C212.401,326.593,228.218,342.418,228.218,361.913z" fill="#6B8C85" id="path-yeywque" />
              <path d="M346.569,361.913c0,19.503-15.817,124.668-35.336,124.668c-19.495,0-35.304-105.173-35.304-124.668 c0-19.495,15.817-35.32,35.304-35.32C330.752,326.593,346.569,342.418,346.569,361.913z" fill="#6B8C85" id="path-imqsbol" />
            </g>
            <g id="path-mzmgqf1-a">
              <g transform="matrix(1,0,0,1,-2.85,-1.22)">
                <path d="M351.705,315.242c0,126.33-44.599,84.259-99.643,84.259c-55.028,0-99.643,42.071-99.643-84.259 c0-72.231,44.631-130.781,99.643-130.781C307.09,184.47,351.705,243.019,351.705,315.242z" id="path-mzmgqf1" />
              </g>
            </g>
            <g id="path-utbq2eq-a">
              <path d="M 351.705 315.242 C 351.705 441.572 307.106 399.501 252.062 399.501 C 197.034 399.501 152.419 441.572 152.419 315.242 C 152.419 243.011 197.05 184.461 252.062 184.461 C 307.09 184.47 351.705 243.019 351.705 315.242 Z" id="path-utbq2eq" />
            </g>
            <path d="M232.629,487.219c0,14.935-17.802,16.904-39.739,16.904s-39.739-1.961-39.739-16.904 c0-14.943,17.802-35.509,39.739-35.509S232.629,472.277,232.629,487.219z" fill="#C90D59" id="path-wxbwwrw" />
            <path d="M232.629,487.219c0,14.935-17.802,16.904-39.739,16.904s-39.739-1.961-39.739-16.904" fill="#AA0B53" id="path-7amk08z" />
            <path d="M350.988,487.219c0,14.935-17.802,16.904-39.739,16.904s-39.739-1.961-39.739-16.904 c0-14.943,17.802-35.509,39.739-35.509S350.988,472.277,350.988,487.219z" fill="#C90D59" id="path-nljd9qm" />
            <path d="M350.988,487.219c0,14.935-17.802,16.904-39.739,16.904s-39.739-1.961-39.739-16.904" fill="#AA0B53" id="path-uszbien" />
            <g id="path-lmotihb-a">
              <path d="M 371.65 102.04 C 328.68 127.97 323.28 218.94 252.08 218.94 C 180.86 218.94 151.36 146.34 129.85 112.2 C 129.85 49.18 173.19 -41.32 252.08 6.94 C 349.5 -48.03 371.65 64.18 371.65 102.04 Z" id="path-lmotihb" fill="#411e0b" fillOpacity="1" />
            </g>
            <path d="M 356.42 124.26 C 356.42 187.27 323.28 218.94 252.08 218.94 C 180.86 218.94 143.12 187.27 143.12 124.26 C 143.12 61.23 167.43 41.21 252.08 47.85 C 343.36 37.56 356.42 61.24 356.42 124.26 Z" fill="#F9BD82" id="path-kzwiw4j" />
            <g id="group-3-c">
              <g id="group-3-a">
                <g id="group-3">
                  <g id="circle-5vhyb1a-i">
                    <g id="circle-5vhyb1a-a">
                      <circle cx="190.748" cy="138.004" r="11.532" fill="#113E49" id="circle-5vhyb1a" />
                    </g>
                  </g>
                  <g id="path-igkge07-i">
                    <g id="path-igkge07-a">
                      <path d="M202.279,137.98c0,6.388-5.167,11.54-11.54,11.54s-11.524-5.152-11.524-11.54" id="path-igkge07" />
                    </g>
                  </g>
                </g>
              </g>
            </g>
            <g id="path-rt5oxqg-i">
              <g id="path-rt5oxqg-a">
                <path d="M213.496,162.028c-0.614,0-1.245-0.221-1.725-0.717c-5.632-5.624-13.107-8.72-21.047-8.72h-0.016 c-7.94,0-15.399,3.104-21,8.712c-0.953,0.953-2.489,0.977-3.434,0.008c-0.953-0.922-0.985-2.458-0.032-3.419 c6.538-6.546,15.218-10.161,24.458-10.161h0.016c9.263,0,17.952,3.592,24.505,10.145c0.937,0.937,0.937,2.505,0,3.434 C214.756,161.808,214.142,162.028,213.496,162.028z" fill="#FFD3C5" id="path-rt5oxqg" />
              </g>
            </g>
            <g id="group-2-c">
              <g id="group-2-a">
                <g id="group-2">
                  <g id="circle-3hwqdxj-i">
                    <g id="circle-3hwqdxj-a">
                      <circle cx="313.423" cy="138.004" r="11.532" fill="#113E49" id="circle-3hwqdxj" />
                    </g>
                  </g>
                  <g id="path-k4vqxm3-i">
                    <g id="path-k4vqxm3-a">
                      <path d="M301.859,137.98c0,6.388,5.152,11.54,11.54,11.54c6.372,0,11.524-5.152,11.524-11.54" id="path-k4vqxm3" />
                    </g>
                  </g>
                </g>
              </g>
            </g>
            <g id="path-w4m1znv-i">
              <g id="path-w4m1znv-a">
                <path d="M290.643,162.028c0.599,0,1.229-0.221,1.709-0.717c5.632-5.624,13.107-8.72,21.047-8.72h0.016 c7.94,0,15.415,3.104,21.016,8.712c0.937,0.953,2.473,0.977,3.434,0.008c0.953-0.922,0.969-2.458,0.016-3.419 c-6.506-6.546-15.218-10.161-24.458-10.161h-0.016c-9.247,0-17.936,3.592-24.505,10.145c-0.922,0.937-0.922,2.505,0,3.434 C289.382,161.808,289.997,162.028,290.643,162.028z" fill="#FFD3C5" id="path-w4m1znv" />
              </g>
            </g>
            <path d="M 223.63 194.64 C 234.2 193.3 236.37 189.18 252.06 189.18 C 268.16 189.18 265.78 191.84 280.49 194.64 C 280.49 198.29 268.3 194.64 252.06 196.12 C 237.78 194.64 223.63 198.29 223.63 194.64 Z" fill="#AA1111" id="path-z7stpax" transform="matrix(1,0,0,1,0,-3.05)" />
            <g id="group-a">
              <g id="group">
                <path d="M345.309,291.643c4.742-14.344-9.862-32.02-32.603-39.534 c-22.709-7.491-138.398-32.713-143.155-18.408c-4.71,14.336,103.353,62.818,126.078,70.309 C318.338,311.517,340.582,305.971,345.309,291.643z" fill="#EDA366" id="path-pbjwip4" />
                <path d="M158.815,291.643c-4.742-14.344,9.862-32.02,32.603-39.534 c22.709-7.491,138.398-32.713,143.155-18.408c4.71,14.336-103.353,62.818-126.078,70.309 C185.785,311.517,163.541,305.971,158.815,291.643z" fill="#F9BD82" id="path-8wvbqub" />
                <path d="M296.369,240.569c-0.859-3.285-1.449-6.412-1.906-9.452c-2.213,0.268-4.466,0.551-6.774,0.859 c0.362,4.506,1.15,9.492,2.528,14.746c1.709,6.498,3.97,12.304,6.412,16.927c2.513-1.371,4.955-2.725,7.31-4.072 C301.048,254.7,298.338,248.084,296.369,240.569z" fill="#7A4E0E" id="path-vj64n8s" />
                <circle cx="291.32" cy="240.561" r="13.627" fill="#38494C" id="circle-wmfifyn" />
                <circle cx="290.265" cy="239.025" r="7.633" fill="#A3E1EF" id="circle-h4qmlr3" />
              </g>
            </g>
            <g id="path-5ir0euf-i">
              <g id="path-5ir0euf-a">
                <g transform="matrix(1,0,0,1,1.17,9.78)">
                  <path d="M243.854,133.608c0,12.123-9.83,21.953-21.937,21.953h-30.208c-12.13,0-21.953-9.83-21.953-21.953V121.73 c0-12.13,9.823-21.961,21.953-21.961h30.208c12.107,0,21.937,9.83,21.937,21.961V133.608z" id="path-5ir0euf" filter="none" fill="#000000" fillOpacity="0.5911112467447917" />
                </g>
              </g>
            </g>
            <path d="M 364.79 108.91 C 364.79 113.98 362.04 118.07 356.99 118.07 L 135.93 118.07 C 130.87 118.07 126.78 113.97 126.78 108.91 L 126.78 108.91 C 128.66 108.91 125.83 108.91 130.89 108.91 L 182.1 108.91 C 187.15 108.91 362.16 108.91 364.79 108.91 L 364.79 108.91 Z" id="path-eh8g23u" />
            <g id="path-rysppx4-i">
              <g id="path-rysppx4-a">
                <g transform="matrix(1,0,0,1,-3.52,9.14)">
                  <path d="M260.269,133.608c0,12.123,9.807,21.953,21.937,21.953h30.184c12.138,0,21.953-9.83,21.953-21.953V121.73 c0-12.13-9.815-21.961-21.953-21.961h-30.184c-12.13,0-21.937,9.83-21.937,21.961V133.608z" id="path-rysppx4" filter="none" fill="#000000" fillOpacity="0.5911112467447917" />
                </g>
              </g>
            </g>
          </g>
        </g>
      </g>
      <path id="circle-e5u-fa7ef7ca" fill="#411e0b" fillOpacity="0.7288892957899306" transform="matrix(0.8848,0,0,0.1419,36.7141,145.7745)" d="M 210.5 244.3 C 210.5 345.81 216.54 222.6 244.15 222.6 C 262.37 220.83 277.22 354.28 278.74 223.91 C 272.14 300.57 269.23 175.59 244.15 168.69 C 216.54 168.69 216.89 283.34 210.5 244.3 Z" />
      <path id="path-l4ogefq" fill="#411e0b" fillOpacity="0.5333333333333333" transform="matrix(-0.88,0,0,0.14,391.56,163.57)" d="M 194.15 269.97 C 185.31 382.16 161.68 391.15 169.54 399.82 C 182.88 424.13 228.07 374.08 258.76 190.72 C 278.43 72.56 281.88 -201.35 281.88 -228.97 C 281.88 -256.58 258 139.17 230.38 139.17 C 197.69 150.18 202.17 149.91 194.15 269.97 Z" />
      <path id="path-649d5fr" fill="#411e0b" fillOpacity="0.5333333333333333" transform="matrix(0.88,0,0,0.14,108.9406,163.5692)" d="M 194.15 269.97 C 185.31 382.16 161.68 391.15 169.54 399.82 C 182.88 424.13 228.07 374.08 258.76 190.72 C 278.43 72.56 281.88 -201.35 281.88 -228.97 C 281.88 -256.58 258.41 140.54 230.79 140.54 C 198.1 151.55 202.17 149.91 194.15 269.97 Z" />
      <g id="path-0acus0d-i">
        <g id="path-0acus0d-a">
          <g transform="matrix(0.6866,0,0,0.1419,38.8384,54.7845)">
            <path id="path-0acus0d" fill="#411e0b" fillOpacity="0.7288892957899306" d="M 192.89 246.75 C 192.89 325.36 216.54 222.6 244.15 222.6 C 262.37 220.83 269.3 271.3 278.11 271.3 C 274.24 248.52 284.74 156.91 244.15 168.69 C 216.54 168.69 204.72 225.9 192.89 246.75 Z" />
          </g>
        </g>
      </g>
      <g id="path-x7pz8y4-i">
        <g id="path-x7pz8y4-a">
          <g transform="matrix(-0.704,0,0,0.14,464.2364,56.42)">
            <path id="path-x7pz8y4" fill="#411e0b" fillOpacity="0.7288892957899306" d="M 192.89 246.75 C 192.89 325.36 216.54 222.6 244.15 222.6 C 262.37 220.83 267 263.3 275.81 263.3 C 271.94 240.52 284.74 156.91 244.15 168.69 C 216.54 168.69 204.72 225.9 192.89 246.75 Z" />
          </g>
        </g>
      </g>
      <path id="path-efqtqdl" fill="#411e0b" fillOpacity="0.7777777777777778" transform="matrix(0.8848,0,0,0.1419,33.8941,178.8345)" d="M 202.96 126.68 C 213.48 329.71 233.12 267.3 244.15 336.47 C 256.48 266.39 276.95 356.91 287.59 126.68 C 277.65 38.62 281.08 195.21 258.93 205.92 C 252.85 208.85 254.49 114.23 244.15 122.6 C 238.02 116.95 234.59 209.15 230.16 205.92 C 202.72 185.9 212.28 28.49 202.96 126.68 Z" />
    </svg>
  );
}
