import { useRef, useEffect, type CSSProperties } from "react";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { MorphSVGPlugin } from "gsap/MorphSVGPlugin";

gsap.registerPlugin(MorphSVGPlugin);

interface UntitledprojectProps {
    /** Size/position it from the outside, e.g. <Untitledproject style={{ width: 240 }} /> */
    className?: string;
    style?: CSSProperties;
}

/**
 * Untitledproject - generated by Stew Factory.
 * Trigger: hover
 * Deps:  npm i gsap @gsap/react
 *
 * Sizing: the SVG fills its container by default - wrap it in a sized element,
 * or pass className / style (e.g. style={{ width: 240, height: 240 }}).
 * overflow:visible lets motion extend past the frame (matches the editor).
 */
export default function Untitledproject({ className, style }: UntitledprojectProps = {}) {
    const root = useRef<SVGSVGElement>(null);
    const tlRef = useRef<gsap.core.Timeline | null>(null);

    useGSAP(() => {
        const tl = gsap.timeline({ paused: true });

        // stew-as-whole · scale
        gsap.set("#stew-as-whole", { scale: 1, svgOrigin: "245.27772521972656 216.16847077448904" });
        tl.to("#stew-as-whole", { scale: 1.154, duration: 0.309, ease: "elastic.out(1, 0.5)" }, 0);

        // stew-as-whole · rotate
        gsap.set("#stew-as-whole", { rotation: 0, svgOrigin: "245.27772521972656 216.16847077448904" });
        tl.to("#stew-as-whole", { rotation: -7.46, duration: 0.309, ease: "elastic.out(1, 0.5)" }, 0);

        // group · scale
        gsap.set("#group", { scale: 1, svgOrigin: "175.572998046875 256.48699951171875" });
        tl.to("#group", { scale: 1.6, duration: 0.334, ease: "power1.inOut" }, 0);

        // group-3 · scale
        gsap.set("#group-3", { scale: 1, svgOrigin: "303.572998046875 253.48700714111328" });
        tl.to("#group-3", { scale: 1.6, duration: 0.309, ease: "power1.inOut" }, 0);

        // group-4 · x
        gsap.set("#group-4", { x: 0, svgOrigin: "305.05792236328125 192.10508728027344" });
        tl.to("#group-4", { x: 3.72, duration: 0.309, ease: "power1.inOut" }, 0);

        // group-4 · y
        gsap.set("#group-4", { y: 0, svgOrigin: "305.05792236328125 192.10508728027344" });
        tl.to("#group-4", { y: -33.15, duration: 0.309, ease: "power1.inOut" }, 0);

        // group-4 · rotate
        gsap.set("#group-4", { rotation: 0, svgOrigin: "305.05792236328125 192.10508728027344" });
        tl.to("#group-4", { rotation: 10.3, duration: 0.309, ease: "power1.inOut" }, 0);

        // path-44 · morph
        gsap.set("#path-44", { attr: { d: "M114.749 234.842C272.368 240.921 526.976 156.74 418.169 156.416C282.159 156.011 -142.906 202.815 114.749 234.842Z" } });
        tl.to("#path-44", { morphSVG: "M133.85627,221.02346 C291.47627,227.10346 495.63627,170.42346 386.82627,170.10346 250.81627,169.69346 69.35627,178.35346 60.42627,206.14346 84.90294,211.10346 109.37961,216.06346 133.85627,221.02346 z", duration: 0.309, ease: "power1.inOut" }, 0);

        // stew-as-whole · x
        gsap.set("#stew-as-whole", { x: 3.96, svgOrigin: "245.27772521972656 216.16847077448904" });
        tlRef.current = tl;
        const cleanups: (() => void)[] = [];

        // right-ear · runAway
        {
            const __el = root.current?.querySelector("#right-ear") as SVGGraphicsElement | null;
            if (__el) {
                const __xTo = gsap.quickTo(__el, "x", { duration: 0.35, ease: "power3" });
                const __yTo = gsap.quickTo(__el, "y", { duration: 0.35, ease: "power3" });
                const __move = (e: MouseEvent) => {
                    const __ap = __el.ownerSVGElement!.createSVGPoint(); __ap.x = 495.1824951171875; __ap.y = 120.42610931396484;
                    const __s = __ap.matrixTransform(__el.getScreenCTM()!); const __cx = __s.x, __cy = __s.y;
                    const dx = __cx - e.clientX, dy = __cy - e.clientY;
                    const d = Math.hypot(dx, dy) || 1;
                    if (d < 120) { const f = (120 - d) / 120; __xTo((dx / d) * 10 * f); __yTo((dy / d) * 10 * f); }
                    else { __xTo(0); __yTo(0); }
                };
                window.addEventListener("mousemove", __move);
                cleanups.push(() => window.removeEventListener("mousemove", __move));
            }
        }

        // left-ear · runAway
        {
            const __el = root.current?.querySelector("#left-ear") as SVGGraphicsElement | null;
            if (__el) {
                const __xTo = gsap.quickTo(__el, "x", { duration: 0.35, ease: "power3" });
                const __yTo = gsap.quickTo(__el, "y", { duration: 0.35, ease: "power3" });
                const __move = (e: MouseEvent) => {
                    const __ap = __el.ownerSVGElement!.createSVGPoint(); __ap.x = 0.0000152587890625; __ap.y = 132.9921417236328;
                    const __s = __ap.matrixTransform(__el.getScreenCTM()!); const __cx = __s.x, __cy = __s.y;
                    const dx = __cx - e.clientX, dy = __cy - e.clientY;
                    const d = Math.hypot(dx, dy) || 1;
                    if (d < 120) { const f = (120 - d) / 120; __xTo((dx / d) * 14 * f); __yTo((dy / d) * 14 * f); }
                    else { __xTo(0); __yTo(0); }
                };
                window.addEventListener("mousemove", __move);
                cleanups.push(() => window.removeEventListener("mousemove", __move));
            }
        }

        // group-8 · breathe
        gsap.set("#group-8", { svgOrigin: "242.572998046875 349.48699951171875" });
        gsap.to("#group-8", { scale: "+=0.06", duration: 2, ease: "sine.inOut", yoyo: true, repeat: -1 });

        // group-8 · followMouse
        {
            const __el = root.current?.querySelector("#group-8") as SVGGraphicsElement | null;
            if (__el) {
                const __xTo = gsap.quickTo(__el, "x", { duration: 0.4, ease: "power3" });
                const __yTo = gsap.quickTo(__el, "y", { duration: 0.4, ease: "power3" });
                const __move = (e: MouseEvent) => {
                    const __r = __el.getBoundingClientRect(); const __cx = __r.left + __r.width / 2, __cy = __r.top + __r.height / 2;
                    const dx = e.clientX - __cx, dy = e.clientY - __cy;
                    const d = Math.hypot(dx, dy) || 1, c = (Math.min(d, 12) / d) * 0.3;
                    __xTo(dx * c); __yTo(dy * c);
                };
                window.addEventListener("mousemove", __move);
                cleanups.push(() => window.removeEventListener("mousemove", __move));
            }
        }

        // group-3 · followMouse
        {
            const __el = root.current?.querySelector("#group-3") as SVGGraphicsElement | null;
            if (__el) {
                const __xTo = gsap.quickTo(__el, "x", { duration: 0.4, ease: "power3" });
                const __yTo = gsap.quickTo(__el, "y", { duration: 0.4, ease: "power3" });
                const __move = (e: MouseEvent) => {
                    const __r = __el.getBoundingClientRect(); const __cx = __r.left + __r.width / 2, __cy = __r.top + __r.height / 2;
                    const dx = e.clientX - __cx, dy = e.clientY - __cy;
                    const d = Math.hypot(dx, dy) || 1, c = (Math.min(d, 40) / d) * 0.3;
                    __xTo(dx * c); __yTo(dy * c);
                };
                window.addEventListener("mousemove", __move);
                cleanups.push(() => window.removeEventListener("mousemove", __move));
            }
        }

        // group-3 · blink
        gsap.timeline({ repeat: -1, repeatDelay: 3 })
            .to("#group-3", { opacity: 0, duration: 0.07, ease: "power1.in" })
            .to("#group-3", { opacity: 1, duration: 0.07, ease: "power1.out" });

        // group · followMouse
        {
            const __el = root.current?.querySelector("#group") as SVGGraphicsElement | null;
            if (__el) {
                const __xTo = gsap.quickTo(__el, "x", { duration: 0.4, ease: "power3" });
                const __yTo = gsap.quickTo(__el, "y", { duration: 0.4, ease: "power3" });
                const __move = (e: MouseEvent) => {
                    const __r = __el.getBoundingClientRect(); const __cx = __r.left + __r.width / 2, __cy = __r.top + __r.height / 2;
                    const dx = e.clientX - __cx, dy = e.clientY - __cy;
                    const d = Math.hypot(dx, dy) || 1, c = (Math.min(d, 40) / d) * 0.3;
                    __xTo(dx * c); __yTo(dy * c);
                };
                window.addEventListener("mousemove", __move);
                cleanups.push(() => window.removeEventListener("mousemove", __move));
            }
        }

        // group · blink
        gsap.timeline({ repeat: -1, repeatDelay: 3 })
            .to("#group", { opacity: 0, duration: 0.07, ease: "power1.in" })
            .to("#group", { opacity: 1, duration: 0.07, ease: "power1.out" });

        // path-40 · followMouse
        {
            const __el = root.current?.querySelector("#path-40") as SVGGraphicsElement | null;
            if (__el) {
                const __xTo = gsap.quickTo(__el, "x", { duration: 0.4, ease: "power3" });
                const __yTo = gsap.quickTo(__el, "y", { duration: 0.4, ease: "power3" });
                const __move = (e: MouseEvent) => {
                    const __r = __el.getBoundingClientRect(); const __cx = __r.left + __r.width / 2, __cy = __r.top + __r.height / 2;
                    const dx = e.clientX - __cx, dy = e.clientY - __cy;
                    const d = Math.hypot(dx, dy) || 1, c = (Math.min(d, 20) / d) * 0.3;
                    __xTo(dx * c); __yTo(dy * c);
                };
                window.addEventListener("mousemove", __move);
                cleanups.push(() => window.removeEventListener("mousemove", __move));
            }
        }

        // ellipse-42 · followMouse
        {
            const __el = root.current?.querySelector("#ellipse-42") as SVGGraphicsElement | null;
            if (__el) {
                const __xTo = gsap.quickTo(__el, "x", { duration: 0.4, ease: "power3" });
                const __yTo = gsap.quickTo(__el, "y", { duration: 0.4, ease: "power3" });
                const __move = (e: MouseEvent) => {
                    const __r = __el.getBoundingClientRect(); const __cx = __r.left + __r.width / 2, __cy = __r.top + __r.height / 2;
                    const dx = e.clientX - __cx, dy = e.clientY - __cy;
                    const d = Math.hypot(dx, dy) || 1, c = (Math.min(d, 20) / d) * 0.3;
                    __xTo(dx * c); __yTo(dy * c);
                };
                window.addEventListener("mousemove", __move);
                cleanups.push(() => window.removeEventListener("mousemove", __move));
            }
        }

        // group-4 · runAway
        {
            const __el = root.current?.querySelector("#group-4") as SVGGraphicsElement | null;
            if (__el) {
                const __xTo = gsap.quickTo(__el, "x", { duration: 0.35, ease: "power3" });
                const __yTo = gsap.quickTo(__el, "y", { duration: 0.35, ease: "power3" });
                const __move = (e: MouseEvent) => {
                    const __r = __el.getBoundingClientRect(); const __cx = __r.left + __r.width / 2, __cy = __r.top + __r.height / 2;
                    const dx = __cx - e.clientX, dy = __cy - e.clientY;
                    const d = Math.hypot(dx, dy) || 1;
                    if (d < 120) { const f = (120 - d) / 120; __xTo((dx / d) * 60 * f); __yTo((dy / d) * 60 * f); }
                    else { __xTo(0); __yTo(0); }
                };
                window.addEventListener("mousemove", __move);
                cleanups.push(() => window.removeEventListener("mousemove", __move));
            }
        }

        // path-24 · followMouse
        {
            const __el = root.current?.querySelector("#path-24") as SVGGraphicsElement | null;
            if (__el) {
                const __xTo = gsap.quickTo(__el, "x", { duration: 0.4, ease: "power3" });
                const __yTo = gsap.quickTo(__el, "y", { duration: 0.4, ease: "power3" });
                const __move = (e: MouseEvent) => {
                    const __r = __el.getBoundingClientRect(); const __cx = __r.left + __r.width / 2, __cy = __r.top + __r.height / 2;
                    const dx = e.clientX - __cx, dy = e.clientY - __cy;
                    const d = Math.hypot(dx, dy) || 1, c = (Math.min(d, 40) / d) * 0.3;
                    __xTo(dx * c); __yTo(dy * c);
                };
                window.addEventListener("mousemove", __move);
                cleanups.push(() => window.removeEventListener("mousemove", __move));
            }
        }

        // path-32 · followMouse
        {
            const __el = root.current?.querySelector("#path-32") as SVGGraphicsElement | null;
            if (__el) {
                const __xTo = gsap.quickTo(__el, "x", { duration: 0.4, ease: "power3" });
                const __yTo = gsap.quickTo(__el, "y", { duration: 0.4, ease: "power3" });
                const __move = (e: MouseEvent) => {
                    const __r = __el.getBoundingClientRect(); const __cx = __r.left + __r.width / 2, __cy = __r.top + __r.height / 2;
                    const dx = e.clientX - __cx, dy = e.clientY - __cy;
                    const d = Math.hypot(dx, dy) || 1, c = (Math.min(d, 40) / d) * 0.3;
                    __xTo(dx * c); __yTo(dy * c);
                };
                window.addEventListener("mousemove", __move);
                cleanups.push(() => window.removeEventListener("mousemove", __move));
            }
        }

        // ellipse-36 · jitter
        {
            const __el = root.current?.querySelector("#ellipse-36");
            if (__el) {
                const __i = 0.5, __r = 0.06;
                const __id = setInterval(() => gsap.to(__el, { x: (Math.random() - 0.5) * 2 * __i, y: (Math.random() - 0.5) * 2 * __i, duration: __r, ease: "none" }), __r * 1000);
                cleanups.push(() => clearInterval(__id));
            }
        }

        // ellipse-38 · jitter
        {
            const __el = root.current?.querySelector("#ellipse-38");
            if (__el) {
                const __i = 0.5, __r = 0.06;
                const __id = setInterval(() => gsap.to(__el, { x: (Math.random() - 0.5) * 2 * __i, y: (Math.random() - 0.5) * 2 * __i, duration: __r, ease: "none" }), __r * 1000);
                cleanups.push(() => clearInterval(__id));
            }
        }

        // ellipse-28 · jitter
        {
            const __el = root.current?.querySelector("#ellipse-28");
            if (__el) {
                const __i = 0.5, __r = 0.06;
                const __id = setInterval(() => gsap.to(__el, { x: (Math.random() - 0.5) * 2 * __i, y: (Math.random() - 0.5) * 2 * __i, duration: __r, ease: "none" }), __r * 1000);
                cleanups.push(() => clearInterval(__id));
            }
        }

        // ellipse-30 · jitter
        {
            const __el = root.current?.querySelector("#ellipse-30");
            if (__el) {
                const __i = 0.5, __r = 0.06;
                const __id = setInterval(() => gsap.to(__el, { x: (Math.random() - 0.5) * 2 * __i, y: (Math.random() - 0.5) * 2 * __i, duration: __r, ease: "none" }), __r * 1000);
                cleanups.push(() => clearInterval(__id));
            }
        }
        return () => cleanups.forEach((fn) => fn());
    }, { scope: root });

    useEffect(() => {
        const el = root.current;
        const tl = tlRef.current;
        if (!el || !tl) return;
        const onEnter = () => tl.play();
        const onLeave = () => tl.reverse();
        el.addEventListener("mouseenter", onEnter);
        el.addEventListener("mouseleave", onLeave);
        return () => {
            el.removeEventListener("mouseenter", onEnter);
            el.removeEventListener("mouseleave", onLeave);
        };
    }, []);

    return (
        <svg ref={root} xmlns="http://www.w3.org/2000/svg" viewBox="273.49 278 476.57 407.91" className={className} style={{ overflow: "visible", ...style }}>
            <g id="Layer_asset-1782241373538" transform="matrix(1,0,0,1,261.42,263.2)">
                <g transform="matrix(0.8593,0,0,0.8254,37.6,40.3282)">
                    <g id="stew-as-whole">
                        <g id="left-ear" data-stew-anchor="0 0" data-semantic-label="left ear">
                            <path d="M1.32723 152.367C73.4364 95.38 224.556 173.948 148.38 260.442C69.0869 350.477 -11.3573 208.83 1.32723 152.367Z" id="path-6" fill="#8f8f8f" />
                            <path d="M24.7828 165.394C76.1419 126.653 184.073 180.442 129.857 239.293C73.4226 300.553 15.8182 203.867 24.7828 165.394Z" id="path-8" fill="#4f4f4f" />
                            <path d="M134.835 201.263C135.928 214.473 104.86 241.873 86.1463 243.422C67.4326 244.971 48.7369 203.626 47.6437 190.417C46.5506 177.207 60.8349 165.243 79.5486 163.695C98.2623 162.146 133.742 188.053 134.835 201.263Z" id="path-10" fill="black" />
                        </g>
                        <g id="right-ear" data-stew-anchor="1 0" data-semantic-label="right ear">
                            <path d="M492.61 136.801C515.28 225.87 381.966 331.877 334.005 227.074C284.081 117.982 446.211 102.215 492.61 136.801Z" id="path-12" fill="#8f8f8f" />
                            <path d="M471.158 152.915C485.618 215.601 392.527 292.26 360.865 218.773C327.908 142.278 439.674 129.056 471.158 152.915Z" id="path-14" fill="#4f4f4f" />
                            <path d="M393.569 238.811C381.06 234.428 368.692 194.893 374.901 177.171C381.11 159.45 426.484 159.217 438.993 163.6C451.502 167.983 456.61 185.902 450.401 203.623C444.192 221.345 406.079 243.194 393.569 238.811Z" id="path-16" fill="black" />
                        </g>
                        <path d="M483.573 328.987C478.268 340.306 447.072 424.215 251.573 431.987C88.0733 438.487 24.5733 352.487 15.0733 335.987C4.11316 316.951 73.5733 148.987 251.573 131.987C403.573 136.987 491.073 312.987 483.573 328.987Z" id="path-18" fill="#8f8f8f" data-semantic-label="whole head" />
                        <g id="group-8" data-semantic-label="whoel mouth">
                            <ellipse cx="242.573" cy="349.487" id="ellipse-20" rx="67" ry="50.5" fill="#D9D9D9" />
                            <ellipse cx="242.573" cy="317.145" id="ellipse-22" rx="20.7931" ry="18.1573" fill="black" />
                        </g>
                        <path d="M205.217 248.302C217.25 273.257 194.717 309.739 154.888 329.786C115.059 349.833 28.0733 329.786 28.0733 329.786C28.0733 329.786 71.4835 259.462 111.312 239.415C151.141 219.367 193.184 223.346 205.217 248.302Z" id="path-24" fill="#4f4f4f" data-semantic-label="elft eye base" />
                        <g id="group" data-semantic-label="left eye">
                            <ellipse cx="175.573" cy="256.487" id="ellipse-26" rx="22" ry="21.5" fill="black" />
                            <ellipse cx="182.573" cy="248.987" id="ellipse-28" rx="8" ry="9" fill="white" />
                            <ellipse cx="169.073" cy="263.987" id="ellipse-30" rx="6.5" ry="7" fill="white" />
                        </g>
                        <path d="M274.361 244.173C262.328 269.128 284.861 305.61 324.69 325.657C364.519 345.704 461.573 325.657 461.573 325.657C461.573 325.657 408.095 255.333 368.266 235.286C328.437 215.239 286.395 219.218 274.361 244.173Z" id="path-32" fill="#4f4f4f" data-semantic-label="right eye base" />
                        <g id="group-3" data-semantic-label="right eye">
                            <ellipse cx="303.573" cy="253.487" id="ellipse-34" rx="22" ry="21.5" fill="black" />
                            <ellipse cx="311.573" cy="244.487" id="ellipse-36" rx="8" ry="8.5" fill="white" />
                            <ellipse cx="296.573" cy="259.487" id="ellipse-38" rx="7" ry="7.5" fill="white" />
                        </g>
                        <path d="M172.573 327.487C172.573 335.496 158.246 341.987 140.573 341.987C122.9 341.987 108.573 335.496 108.573 327.487C108.573 319.479 122.9 312.987 140.573 312.987C158.246 312.987 172.573 319.479 172.573 327.487Z" id="path-40" fill="#FFA4A4" data-semantic-label="left blush" />
                        <ellipse cx="351.573" cy="327.487" id="ellipse-42" rx="32" ry="14.5" fill="#FFA4A4" data-semantic-label="rigth blush" />
                        <g id="group-4" data-stew-anchor="0.6608942555319838 0.8169259836586946" data-semantic-label="hat">
                            <path d="M114.749 234.842C272.368 240.921 526.976 156.74 418.169 156.416C282.159 156.011 -142.906 202.815 114.749 234.842Z" id="path-44" fill="#5d2856" />
                            <path d="M291.232 25.5249C184.277 74.8495 152.31 13.0252 155.338 0.795283L111.487 177.885C98.9437 207.452 264.056 201.888 353.532 178.642L323.625 1.15062C323.671 0.69467 323.604 0.308742 323.432 -1.51555e-06L323.625 1.15062C323.214 5.29089 313.61 15.2047 291.232 25.5249Z" id="path-46" fill="#605260" clipRule="evenodd" fillRule="evenodd" />
                            <path d="M155.338 0.795283C152.31 13.0252 184.277 74.8495 291.232 25.5249C313.61 15.2047 323.214 5.29089 323.625 1.15062L323.432 -1.51555e-06C216.586 51.9144 176.537 -0.0684367 155.338 0.795283Z" id="path-48" fill="#a1a1a1" />
                        </g>
                    </g>
                </g>
            </g>
        </svg>
    );
}
